name: common_crypto
description: apple CommonCrypto ffi bindings for Dart.
version: 0.0.1
homepage: https://github.com/MixinNetwork/flutter-plugins

environment:
  sdk: '>=3.1.0 <4.0.0'

platforms:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  pointycastle: ^3.7.3